### ISSUE TITLE
Change deploy to Netlify

### ISSUE THREAD

**Issue by vikiival** [kodadot/sub-scaffold#28]
- [x] Opensource this repo
- [x] publish on netlify [sub-scaffold.netlify.app](https://sub-scaffold.netlify.app/)
- [ ] Wait for first build

**Comment by vikiival** [comment]
<img width="955" alt="Screenshot 2022-11-09 at 17 07 54" src="https://user-images.githubusercontent.com/22471030/200880961-61d54700-8eff-4164-a46a-4d5807053ca1.png">

Current setup doesnt work well with netlify

**Comment by vikiival** [comment]
@brano-hozza invited you to my private project so may chceck the config?

**Comment by brano-hozza** [comment]
@vikiival sure
