### ISSUE TITLE
Proper dark mode

### ISSUE THREAD

**Issue by vikiival** [kodadot/sub-scaffold#39]
The current dark mode does not look good on mobile.

![IMG_5021](https://user-images.githubusercontent.com/22471030/204926428-843a7ab7-da36-4508-83ef-0a8b7601c1b0.PNG)

It would be nice also leverage naive ui dark mode switch so people can change :) 🔥 

also could be added to navbar in #36

**Comment by brano-hozza** [comment]
Already done 🚀
