### ISSUE TITLE
Create Address Component

### ISSUE THREAD

**Issue by dudo50** [kodadot/sub-scaffold#9]
Create a component, that will handle addresses (eg AccountID32, AccountKey20 and will verify them)

**Comment by dudo50** [comment]
Let me clarify this issue a little closer.
Suppose we have user entering address that they wish to transfer their funds to (on other network). We need to handle situations where they type in wrong address (for example too much characters or too little characters). There are mainly two kinds of addresses we are looking to handle:
- AccountKey20, This address is also used on Ethereum and EVM support nodes use it (Moonbeam for example)
- AccountId32, Standard polkadot address format.

Way we handle if AccountKey20 is valid at the moment in Paraspell/SDK is by importing ethers and checking if function returns true. This is sufficient and can be integrated.
On Polkadot however we only check if size of string is long enough as we have not yet found a way to check for this more efficiently. If possible, explore this a little and see if there is any way to validate AccountId32 address types. We generally want to give user warning for typing in wrong address format, but non invasive although it should be clear, that address they pasted is not compliant..

Example of each:

AccountKey20 - 0xa085190c859eAe92bCCED9CE05b10DDb363FE5Ea
AccountId32 - 1jbEnzKdwYZMDsmz5ee2L1H6CMfW1Za3MqjtXFwmeZsRe9P

**Comment by brano-hozza** [comment]
I will look into kodadot implementation for solution
